// ═══════════════════════════════════════════════════════════
// Baytzaki — Complete Egypt Smart Home Products Database
// 200+ products across 20+ categories, 18+ brands
// ═══════════════════════════════════════════════════════════

export type Product = {
  id: string;
  name: string;
  brand: string;
  category: string;
  subcategory: string;
  protocol: string;
  description: string;
  features: string[];
  priceEGP: number;
  priceRange: "Low" | "Medium" | "Premium";
  badge?: string;
  badgeColor?: string;
  store: string;
  storeType: "Online" | "Offline" | "Both";
  url: string;
  inStock: boolean;
  compatibility: string[];
  installation: "DIY" | "Electrician" | "Technician";
  useCase: string[];
  sku: string;
  image?: string;
  featured?: boolean;
  isNew?: boolean;
};

export const CATEGORIES = [
  "All",
  "Smart Switches",
  "Smart Plugs",
  "Smart Lighting",
  "Smart Cameras",
  "Smart Locks",
  "Video Intercom",
  "Smart Curtains",
  "Smart Sensors",
  "Gateways & Hubs",
  "Control Panels",
  "Smart Climate",
  "Energy Management",
  "Smart Doorbells",
  "Staircase Lighting",
  "Smart Appliances",
  "Water Management",
  "Security Systems",
  "Smart Audio",
  "Bundles & Kits",
];

export const BRANDS = [
  "All",
  "SONOFF",
  "TP-Link Tapo",
  "EZVIZ",
  "Aqara",
  "Tuya",
  "Govee",
  "Fibaro",
  "HDL",
  "LEZN",
  "PANDA",
  "Hikvision",
  "Commax",
  "Akuvox",
  "Shelly",
  "Xiaomi",
  "BroadLink",
  "SwitchBot",
  "Philips Hue",
  "Yeelight",
  "Amazon",
  "Google",
];

export const ALL_PRODUCTS: Product[] = [

  // ── SONOFF WALL SWITCHES ────────────────────────────────────
  {
    id: "snf-t5-4c-120",
    name: "SONOFF TX Ultimate T5 4-Gang (120 Type)",
    brand: "SONOFF", category: "Smart Switches", subcategory: "WiFi Touch Wall Switch",
    protocol: "WiFi",
    description: "Premium 4-gang full-glass touch switch with ambient LED ring lighting. The flagship of SONOFF's wall switch lineup — stunning in any villa or modern apartment.",
    features: ["4-gang 120-type panel", "Full-glass touch surface", "Ambient LED strip", "eWeLink app", "Alexa & Google", "Schedule & timer", "2-way control"],
    priceEGP: 2000, priceRange: "Medium", badge: "Best Seller", badgeColor: "aurora",
    store: "SONOFF Egypt", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "Electrician", useCase: ["Lighting", "Automation"], sku: "SNF-T5-4C-120", featured: true,
  },
  {
    id: "snf-t5-3c-120",
    name: "SONOFF TX Ultimate T5 3-Gang (120 Type)",
    brand: "SONOFF", category: "Smart Switches", subcategory: "WiFi Touch Wall Switch",
    protocol: "WiFi",
    description: "3-gang 120-type glass switch with ambient LED — ideal for bedrooms and open-plan spaces that need multi-light control in one elegant panel.",
    features: ["3-gang 120-type", "Full-glass panel", "LED ambient light", "Voice control", "Timer & scenes"],
    priceEGP: 1800, priceRange: "Medium",
    store: "SONOFF Egypt", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "Electrician", useCase: ["Lighting", "Automation"], sku: "SNF-T5-3C-120",
  },
  {
    id: "snf-t5-2c-120",
    name: "SONOFF TX Ultimate T5 2-Gang (120 Type)",
    brand: "SONOFF", category: "Smart Switches", subcategory: "WiFi Touch Wall Switch",
    protocol: "WiFi",
    description: "2-gang version of the TX Ultimate series — minimalist design with ambient strip for bedrooms and corridors.",
    features: ["2-gang 120-type", "Full-glass touch", "Ambient LED", "App + voice control"],
    priceEGP: 1700, priceRange: "Medium",
    store: "SONOFF Egypt", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "Electrician", useCase: ["Lighting", "Automation"], sku: "SNF-T5-2C-120",
  },
  {
    id: "snf-t2-uk-3c",
    name: "SONOFF TX T2 UK 3-Gang WiFi Switch",
    brand: "SONOFF", category: "Smart Switches", subcategory: "WiFi Touch Wall Switch",
    protocol: "WiFi",
    description: "UK-type 3-gang smart switch — control three lighting circuits with one panel. Popular in Egyptian hallways and lounge areas.",
    features: ["3-gang UK type", "Remote control", "Alexa & Google", "Scheduling", "eWeLink scenes"],
    priceEGP: 1300, priceRange: "Low",
    store: "SONOFF Egypt / Amazon.eg", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "Electrician", useCase: ["Lighting", "Automation"], sku: "SNF-T2-UK-3C",
  },
  {
    id: "snf-t2-uk-2c",
    name: "SONOFF TX T2 UK 2-Gang WiFi Switch",
    brand: "SONOFF", category: "Smart Switches", subcategory: "WiFi Touch Wall Switch",
    protocol: "WiFi",
    description: "2-gang UK wall switch — great entry to smart lighting for bedrooms and bathrooms.",
    features: ["2-gang UK type", "Touch control", "eWeLink app", "Voice control", "Smart automation"],
    priceEGP: 1100, priceRange: "Low",
    store: "SONOFF Egypt / Amazon.eg", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "Electrician", useCase: ["Lighting", "Automation"], sku: "SNF-T2-UK-2C",
  },
  {
    id: "snf-t2-uk-1c",
    name: "SONOFF TX T2 UK 1-Gang WiFi Switch",
    brand: "SONOFF", category: "Smart Switches", subcategory: "WiFi Touch Wall Switch",
    protocol: "WiFi",
    description: "Entry-level single-gang smart switch — the simplest way to make one light smart without touching the bulb.",
    features: ["1-gang UK type", "Touch panel", "Remote control", "Voice control", "Timer"],
    priceEGP: 950, priceRange: "Low",
    store: "SONOFF Egypt", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "Electrician", useCase: ["Lighting", "Automation"], sku: "SNF-T2-UK-1C",
  },
  {
    id: "snf-m5-matter-2c",
    name: "SONOFF M5 Matter Switch 2-Gang",
    brand: "SONOFF", category: "Smart Switches", subcategory: "Matter Wall Switch",
    protocol: "Matter / WiFi",
    description: "Future-proof 2-gang switch with Matter certification — connects directly to Apple Home, Google Home, and Alexa without any hub or bridge.",
    features: ["Matter certified", "2-gang 120-type", "Works with HomeKit", "Google Home native", "Amazon Alexa", "Local control"],
    priceEGP: 1600, priceRange: "Medium", badge: "New", badgeColor: "ember",
    store: "SONOFF Egypt", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "eWeLink"],
    installation: "Electrician", useCase: ["Lighting", "Automation"], sku: "SNF-M5-MATTER-2C", isNew: true,
  },
  {
    id: "snf-zbm5-1c",
    name: "SONOFF M5 Zigbee Switch 1-Gang",
    brand: "SONOFF", category: "Smart Switches", subcategory: "Zigbee Wall Switch",
    protocol: "Zigbee",
    description: "Zigbee-based wall switch for rock-solid automation — no WiFi congestion, faster response, and works as a Zigbee mesh repeater.",
    features: ["1-gang Zigbee 3.0", "Hub required", "Local control", "No internet delay", "eWeLink / Home Assistant"],
    priceEGP: 1100, priceRange: "Low",
    store: "SONOFF Egypt", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: true, compatibility: ["Alexa", "Google Home", "Home Assistant", "eWeLink"],
    installation: "Electrician", useCase: ["Lighting", "Automation"], sku: "SNF-ZBM5-1C",
  },

  // ── SONOFF DIY SWITCHES ─────────────────────────────────────
  {
    id: "snf-basic-r2",
    name: "SONOFF BASIC R2 WiFi Switch Module",
    brand: "SONOFF", category: "Smart Switches", subcategory: "WiFi DIY Module",
    protocol: "WiFi",
    description: "The classic that started it all — the most affordable way to make any 220V device smart. Hides inside walls, panels, or distribution boxes.",
    features: ["10A / 2200W", "In-wall installation", "App + voice control", "Timer & schedule", "eWeLink app", "DIY friendly"],
    priceEGP: 280, priceRange: "Low", badge: "Most Popular", badgeColor: "electric",
    store: "SONOFF Egypt / Amazon.eg / Jumia", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "DIY", useCase: ["Automation", "Lighting"], sku: "SNF-BASIC-R2", featured: true,
  },
  {
    id: "snf-mini-r2",
    name: "SONOFF MINI R2 Ultra-Small WiFi Switch",
    brand: "SONOFF", category: "Smart Switches", subcategory: "WiFi DIY Module",
    protocol: "WiFi",
    description: "Tiny enough to fit behind any standard wall switch — makes existing lights smart with zero visible change to your apartment.",
    features: ["Fits in switch box", "2-way control", "10A load", "eWeLink app", "Alexa & Google", "External switch support"],
    priceEGP: 350, priceRange: "Low",
    store: "SONOFF Egypt / Amazon.eg", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "DIY", useCase: ["Lighting", "Automation"], sku: "SNF-MINI-R2",
  },
  {
    id: "snf-minir4",
    name: "SONOFF MINIR4 Extreme Mini Switch",
    brand: "SONOFF", category: "Smart Switches", subcategory: "WiFi DIY Module",
    protocol: "WiFi",
    description: "The most advanced MINI — detach relay mode for 2-way control, garage door support, and Matter-ready firmware.",
    features: ["Detach relay mode", "Garage door support", "10A", "Matter-ready", "eWeLink / Alexa / Google"],
    priceEGP: 550, priceRange: "Low",
    store: "Amazon.eg / SONOFF Egypt", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Home Assistant", "eWeLink"],
    installation: "DIY", useCase: ["Automation", "Lighting"], sku: "SNF-MINIR4",
  },
  {
    id: "snf-zbminil2",
    name: "SONOFF ZBMINI-L2 Zigbee No-Neutral Switch",
    brand: "SONOFF", category: "Smart Switches", subcategory: "Zigbee DIY Module",
    protocol: "Zigbee",
    description: "Zigbee switch for older Egyptian homes with no neutral wire — the most popular solution for legacy electrical installations.",
    features: ["No neutral required", "Zigbee 3.0", "Ultra-compact", "Works 3W+ bulbs", "Hub required"],
    priceEGP: 650, priceRange: "Low", badge: "Egypt Favourite", badgeColor: "plasma",
    store: "Amazon.eg / SONOFF Egypt", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Home Assistant", "eWeLink"],
    installation: "DIY", useCase: ["Lighting", "Automation"], sku: "SNF-ZBMINIL2", featured: true,
  },
  {
    id: "snf-pow-r3",
    name: "SONOFF POW R3 25A Energy Monitor Switch",
    brand: "SONOFF", category: "Smart Switches", subcategory: "WiFi Power Monitor Switch",
    protocol: "WiFi",
    description: "Heavy-duty smart switch with real-time energy monitoring — track AC units, water heaters, and high-load appliances easily.",
    features: ["25A / 5500W", "Real-time energy monitoring", "Overcurrent protection", "App alerts", "eWeLink", "Voice control"],
    priceEGP: 950, priceRange: "Low",
    store: "SONOFF Egypt / Amazon.eg", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "Electrician", useCase: ["Energy Saving", "Automation"], sku: "SNF-POW-R3",
  },
  {
    id: "snf-th-elite",
    name: "SONOFF TH Elite WiFi Thermostat Switch",
    brand: "SONOFF", category: "Smart Climate", subcategory: "WiFi Thermostat Switch",
    protocol: "WiFi",
    description: "Smart switch with external sensor port — automatically controls your AC, fan, or heater based on real room temperature and humidity.",
    features: ["Temperature & humidity sensor port", "16A relay", "Temperature automation", "eWeLink app", "Alexa & Google"],
    priceEGP: 850, priceRange: "Low",
    store: "SONOFF Egypt / Amazon.eg", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink", "Home Assistant"],
    installation: "DIY", useCase: ["Climate", "Energy Saving"], sku: "SNF-TH-ELITE",
  },

  // ── SONOFF CONTROL PANELS ──────────────────────────────────
  {
    id: "snf-nspanel-pro-120",
    name: "SONOFF NSPanel Pro 120 Smart Control Panel",
    brand: "SONOFF", category: "Control Panels", subcategory: "Smart Wall Panel",
    protocol: "WiFi / Zigbee",
    description: "The ultimate smart home wall panel — 4.7\" touch screen controls lights, cameras, sensors, and energy monitoring from one sleek panel.",
    features: ["4.7\" touch display", "Built-in Zigbee hub", "Camera monitoring", "Energy tracking", "Thermostat control", "eWeLink ecosystem"],
    priceEGP: 4500, priceRange: "Premium", badge: "AI Pick", badgeColor: "electric",
    store: "SONOFF Egypt / Amazon.eg", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink", "Home Assistant"],
    installation: "Electrician", useCase: ["Automation", "Energy", "Security"], sku: "SNF-NSPANEL-PRO-120", featured: true,
  },
  {
    id: "snf-nspanel-us",
    name: "SONOFF NSPanel US Smart Home Panel",
    brand: "SONOFF", category: "Control Panels", subcategory: "Smart Wall Panel",
    protocol: "WiFi / Zigbee",
    description: "US-type wall panel with 3.5\" color touch screen — acts as smart switch, thermostat controller, and Zigbee hub all in one device.",
    features: ["3.5\" color touchscreen", "2-gang switch + thermostat", "Zigbee hub", "eWeLink app", "Temperature display"],
    priceEGP: 2800, priceRange: "Medium",
    store: "SONOFF Egypt", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "Electrician", useCase: ["Automation", "Climate"], sku: "SNF-NSPANEL-US",
  },

  // ── SONOFF GATEWAYS & SENSORS ──────────────────────────────
  {
    id: "snf-zbbridge-pro",
    name: "SONOFF Zigbee Bridge Pro Gateway",
    brand: "SONOFF", category: "Gateways & Hubs", subcategory: "Zigbee Gateway",
    protocol: "Zigbee / WiFi",
    description: "Connect up to 128 Zigbee devices to your app — the brain that gives all your sensors, switches, and bulbs cloud connectivity.",
    features: ["128 device support", "Zigbee 3.0", "OTA updates", "eWeLink app", "Alexa / Google", "Local control"],
    priceEGP: 900, priceRange: "Low",
    store: "SONOFF Egypt / Amazon.eg", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Home Assistant", "eWeLink"],
    installation: "DIY", useCase: ["Automation"], sku: "SNF-ZBBRIDGE-PRO",
  },
  {
    id: "snf-ihost",
    name: "SONOFF iHost Local Smart Home Hub",
    brand: "SONOFF", category: "Gateways & Hubs", subcategory: "Local Smart Hub",
    protocol: "WiFi / Zigbee",
    description: "Privacy-first local hub — runs entirely without the cloud. Full Home Assistant compatibility and Docker app support for power users.",
    features: ["100% local control", "No cloud required", "Zigbee + WiFi", "Home Assistant", "Docker support", "2/4GB RAM options"],
    priceEGP: 3500, priceRange: "Medium", badge: "Pro Choice", badgeColor: "plasma",
    store: "SONOFF Egypt / Amazon.eg", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Home Assistant", "eWeLink"],
    installation: "DIY", useCase: ["Automation"], sku: "SNF-IHOST",
  },
  {
    id: "snf-snzb-02d",
    name: "SONOFF SNZB-02D Zigbee Temp & Humidity Sensor",
    brand: "SONOFF", category: "Smart Sensors", subcategory: "Temperature & Humidity",
    protocol: "Zigbee",
    description: "Smart sensor with LCD display — monitor room temperature and humidity in real time and trigger automations when limits are crossed.",
    features: ["LCD display", "±0.2°C accuracy", "Zigbee 3.0", "Battery powered", "Alert notifications", "Hub required"],
    priceEGP: 650, priceRange: "Low",
    store: "SONOFF Egypt / Amazon.eg", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink", "Home Assistant"],
    installation: "DIY", useCase: ["Climate", "Comfort"], sku: "SNF-SNZB-02D",
  },
  {
    id: "snf-snzb-03p",
    name: "SONOFF SNZB-03P Zigbee Motion Sensor",
    brand: "SONOFF", category: "Smart Sensors", subcategory: "Motion Sensor",
    protocol: "Zigbee",
    description: "Wide-angle motion sensor with 5-year battery life — triggers lights, alarms, or cameras automatically when movement is detected.",
    features: ["Wide 110° detection", "Zigbee 3.0", "5-year battery life", "Instant alerts", "Smart automation trigger"],
    priceEGP: 700, priceRange: "Low",
    store: "SONOFF Egypt / Amazon.eg", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink", "Home Assistant"],
    installation: "DIY", useCase: ["Security", "Automation"], sku: "SNF-SNZB-03P",
  },
  {
    id: "snf-snzb-04p",
    name: "SONOFF SNZB-04P Zigbee Door/Window Sensor",
    brand: "SONOFF", category: "Smart Sensors", subcategory: "Door/Window Sensor",
    protocol: "Zigbee",
    description: "Know instantly when a door or window opens — real-time alerts, alarm triggers, and smart automations based on entry events.",
    features: ["Open/close detection", "Tamper alert", "5-year battery", "Zigbee 3.0", "20mm mounting range"],
    priceEGP: 949, priceRange: "Low",
    store: "Aura Smart Home / Amazon.eg", storeType: "Both", url: "https://aura.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink", "Home Assistant"],
    installation: "DIY", useCase: ["Security", "Automation"], sku: "SNF-SNZB-04P",
  },
  {
    id: "snf-snzb-01p",
    name: "SONOFF SNZB-01P Zigbee Wireless Button",
    brand: "SONOFF", category: "Smart Sensors", subcategory: "Wireless Button",
    protocol: "Zigbee",
    description: "A tiny wireless button that triggers any automation — single press, double press, or long press for three different scenes.",
    features: ["Single / double / long press", "Battery powered", "Zigbee 3.0", "Smart scene trigger", "Hub required"],
    priceEGP: 450, priceRange: "Low",
    store: "SONOFF Egypt / Amazon.eg", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink", "Home Assistant"],
    installation: "DIY", useCase: ["Automation"], sku: "SNF-SNZB-01P",
  },
  {
    id: "snf-swv",
    name: "SONOFF SWV Zigbee Smart Water Valve",
    brand: "SONOFF", category: "Water Management", subcategory: "Smart Water Valve",
    protocol: "Zigbee",
    description: "Control your water supply automatically — schedule watering, detect leaks, and shut off remotely to prevent flood damage.",
    features: ["Zigbee 3.0", "Schedule watering", "App remote control", "Alexa & Google", "Hub required"],
    priceEGP: 1800, priceRange: "Medium",
    store: "SONOFF Egypt / Amazon.eg", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: false, compatibility: ["Alexa", "Google Home", "eWeLink", "Home Assistant"],
    installation: "Technician", useCase: ["Energy Saving", "Automation"], sku: "SNF-SWV",
  },

  // ── SONOFF LIGHTING ────────────────────────────────────────
  {
    id: "snf-l2-5m",
    name: "SONOFF L2 RGB LED Strip 5m",
    brand: "SONOFF", category: "Smart Lighting", subcategory: "LED Strip",
    protocol: "WiFi",
    description: "5-meter RGB smart LED strip for accent lighting behind TVs, under cabinets, or along walls. Syncs with music and smart scenes.",
    features: ["5 meters RGBW", "Music sync mode", "16M colors", "App + voice control", "Alexa & Google", "eWeLink scenes"],
    priceEGP: 950, priceRange: "Low",
    store: "SONOFF Egypt / Amazon.eg", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "DIY", useCase: ["Lighting", "Comfort"], sku: "SNF-L2-5M",
  },
  {
    id: "snf-b02-f",
    name: "SONOFF B02-F Smart Filament Bulb E27",
    brand: "SONOFF", category: "Smart Lighting", subcategory: "Smart Bulb",
    protocol: "WiFi",
    description: "Edison-style smart filament bulb — warm dimmable glow controlled from your phone. No hub needed, just screw in and connect.",
    features: ["E27 base", "Dimmable warm white", "Vintage filament look", "No hub required", "Voice control", "App scheduling"],
    priceEGP: 450, priceRange: "Low",
    store: "SONOFF Egypt / Amazon.eg", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "DIY", useCase: ["Lighting", "Comfort"], sku: "SNF-B02-F",
  },

  // ── SONOFF CURTAIN ─────────────────────────────────────────
  {
    id: "snf-curtain-5m",
    name: "SONOFF Smart Curtain Motor Kit (5m Rail)",
    brand: "SONOFF", category: "Smart Curtains", subcategory: "Curtain Motor Kit",
    protocol: "WiFi",
    description: "Complete smart curtain kit with 5-meter motorized rail — automate your curtains via app, voice, or schedule. No rewiring needed.",
    features: ["5m rail included", "Alexa & Google", "Schedule open/close", "Manual pull trigger", "Memory position", "Quiet motor"],
    priceEGP: 4800, priceRange: "Medium", badge: "Complete Kit", badgeColor: "aurora",
    store: "SONOFF Egypt", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "Technician", useCase: ["Comfort", "Automation"], sku: "SNF-CURTAIN-5M", featured: true,
  },

  // ── SONOFF SMART PLUGS ─────────────────────────────────────
  {
    id: "snf-s26r2",
    name: "SONOFF S26R2TPF WiFi Smart Plug EU",
    brand: "SONOFF", category: "Smart Plugs", subcategory: "WiFi Smart Socket",
    protocol: "WiFi",
    description: "Transform any EU socket into a smart outlet — control appliances remotely, set schedules, and protect against overload.",
    features: ["EU socket type", "Remote on/off", "Timer & schedule", "Voice control", "eWeLink app", "Overload protection"],
    priceEGP: 535, priceRange: "Low",
    store: "Amazon.eg / SONOFF Egypt / Jumia", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "DIY", useCase: ["Energy Saving", "Automation"], sku: "SNF-S26R2",
  },

  // ── TP-LINK TAPO CAMERAS ──────────────────────────────────
  {
    id: "tapo-c200",
    name: "TP-Link Tapo C200 Pan/Tilt 1080p Camera",
    brand: "TP-Link Tapo", category: "Smart Cameras", subcategory: "Indoor Pan/Tilt Camera",
    protocol: "WiFi",
    description: "Egypt's most popular indoor smart camera — 360° pan/tilt with night vision, two-way audio, and motion alerts. The ultimate starter security camera.",
    features: ["1080p Full HD", "360° pan/tilt", "Night vision 10m", "2-way audio", "Motion detection", "microSD up to 128GB"],
    priceEGP: 520, priceRange: "Low", badge: "#1 Best Seller", badgeColor: "aurora",
    store: "Noon / Amazon.eg / Jumia / B.TECH", storeType: "Both", url: "https://noon.com/egypt-en",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Security", "Baby Monitor"], sku: "TAPO-C200", featured: true,
  },
  {
    id: "tapo-c210",
    name: "TP-Link Tapo C210 2K Pan/Tilt Indoor Camera",
    brand: "TP-Link Tapo", category: "Smart Cameras", subcategory: "Indoor Pan/Tilt Camera",
    protocol: "WiFi",
    description: "Upgrade to 2K clarity — sharper footage, smarter person detection, and seamless Tapo ecosystem integration.",
    features: ["2K 3MP resolution", "360° coverage", "Person detection", "2-way audio", "Night vision", "Cloud + SD storage"],
    priceEGP: 780, priceRange: "Low",
    store: "Noon / Amazon.eg / B.TECH", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Security", "Baby Monitor"], sku: "TAPO-C210",
  },
  {
    id: "tapo-c220",
    name: "TP-Link Tapo C220 AI 2K Pan/Tilt Camera",
    brand: "TP-Link Tapo", category: "Smart Cameras", subcategory: "Indoor Pan/Tilt Camera",
    protocol: "WiFi",
    description: "AI-powered 2K camera that automatically identifies people, pets, and unusual sounds — smarter security with fewer false alarms.",
    features: ["2K 4MP AI camera", "360° pan/tilt", "AI person/pet detection", "2-way audio", "Night vision", "microSD + cloud"],
    priceEGP: 1100, priceRange: "Low", badge: "AI Powered", badgeColor: "electric",
    store: "Amazon.eg / Noon / B.TECH", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Security", "Baby Monitor"], sku: "TAPO-C220",
  },
  {
    id: "tapo-c310",
    name: "TP-Link Tapo C310 Outdoor 3MP WiFi Camera",
    brand: "TP-Link Tapo", category: "Smart Cameras", subcategory: "Outdoor Camera",
    protocol: "WiFi",
    description: "Weatherproof outdoor camera with 3MP resolution — monitors your entrance, garden, or parking area day and night reliably.",
    features: ["3MP resolution", "IP66 weatherproof", "Night vision 30m", "Motion detection", "microSD + cloud", "2-way audio"],
    priceEGP: 1277, priceRange: "Low",
    store: "Amazon.eg / Noon / Jumia / B.TECH", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Security", "Outdoor"], sku: "TAPO-C310", featured: true,
  },
  {
    id: "tapo-c510w",
    name: "TP-Link Tapo C510W Outdoor Pan/Tilt 2K Camera",
    brand: "TP-Link Tapo", category: "Smart Cameras", subcategory: "Outdoor Pan/Tilt Camera",
    protocol: "WiFi",
    description: "Full outdoor pan/tilt with 360° horizontal rotation and 2K quality — covers an entire yard or parking area automatically with motion tracking.",
    features: ["2K HD outdoor", "360° pan/tilt", "Motion tracking", "Color night vision", "IP66", "Alexa & Google"],
    priceEGP: 2200, priceRange: "Medium",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Security", "Outdoor"], sku: "TAPO-C510W",
  },
  {
    id: "tapo-c410",
    name: "TP-Link Tapo C410 Wire-Free Battery Camera",
    brand: "TP-Link Tapo", category: "Smart Cameras", subcategory: "Wire-Free Battery Camera",
    protocol: "WiFi",
    description: "No wires, no hassle — mount anywhere outdoors. Solar-compatible 2K battery camera with color night vision and AI detection.",
    features: ["2K 3MP wireless", "Rechargeable battery", "IP65 weatherproof", "Color night vision", "AI person detection", "Solar compatible"],
    priceEGP: 2100, priceRange: "Medium",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Security", "Outdoor"], sku: "TAPO-C410",
  },

  // ── TAPO PLUGS & LIGHTING ──────────────────────────────────
  {
    id: "tapo-p100",
    name: "TP-Link Tapo P100 WiFi Smart Plug",
    brand: "TP-Link Tapo", category: "Smart Plugs", subcategory: "WiFi Smart Socket",
    protocol: "WiFi",
    description: "Simple, reliable smart plug — control any device remotely through the Tapo app. No hub needed, works in minutes straight from the box.",
    features: ["EU socket", "Remote on/off", "App scheduling", "Timer function", "No hub required", "Alexa & Google"],
    priceEGP: 380, priceRange: "Low", badge: "Top Starter", badgeColor: "aurora",
    store: "Amazon.eg / Noon / Jumia / B.TECH", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Energy Saving", "Automation"], sku: "TAPO-P100", featured: true,
  },
  {
    id: "tapo-p110",
    name: "TP-Link Tapo P110 Energy Monitoring Smart Plug",
    brand: "TP-Link Tapo", category: "Smart Plugs", subcategory: "WiFi Energy Monitor Plug",
    protocol: "WiFi",
    description: "Smart plug that tracks exactly how much electricity each device uses — identify energy hogs and cut your electricity bill.",
    features: ["EU socket", "Real-time energy monitoring", "Monthly usage reports", "Timer & schedule", "Alexa & Google", "Overload protection"],
    priceEGP: 550, priceRange: "Low",
    store: "Amazon.eg / Noon / Jumia", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Energy Saving", "Automation"], sku: "TAPO-P110",
  },
  {
    id: "tapo-l530e",
    name: "TP-Link Tapo L530E Smart RGBW Bulb E27",
    brand: "TP-Link Tapo", category: "Smart Lighting", subcategory: "RGBW Smart Bulb",
    protocol: "WiFi",
    description: "Full-color smart bulb with 16M colors — set the mood for movies, parties, or relaxation at the tap of a button. No hub needed.",
    features: ["16M RGBW colors", "E27 base", "Dimmable", "Music sync", "No hub required", "Alexa & Google"],
    priceEGP: 450, priceRange: "Low",
    store: "Amazon.eg / Noon / Jumia / B.TECH", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Lighting", "Comfort"], sku: "TAPO-L530E",
  },
  {
    id: "tapo-l920",
    name: "TP-Link Tapo L920 RGBIC LED Strip 5m",
    brand: "TP-Link Tapo", category: "Smart Lighting", subcategory: "RGBIC LED Strip",
    protocol: "WiFi",
    description: "Premium RGBIC LED strip — multiple colors simultaneously across the strip for stunning backlight effects behind TVs and along walls.",
    features: ["5m RGBIC strip", "Multi-zone lighting", "Music sync", "Flexible zones", "Tapo app", "Alexa & Google"],
    priceEGP: 1200, priceRange: "Low",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Lighting", "Comfort"], sku: "TAPO-L920",
  },

  // ── TAPO SECURITY HUB & SENSORS ───────────────────────────
  {
    id: "tapo-h200",
    name: "TP-Link Tapo H200 Smart Home Hub",
    brand: "TP-Link Tapo", category: "Gateways & Hubs", subcategory: "Smart Security Hub",
    protocol: "WiFi / 868MHz",
    description: "Security hub with built-in 100dB siren — connects all Tapo sensors for a complete home alarm system managed from one app.",
    features: ["100dB built-in siren", "Connects sensors", "Alarm system hub", "App alerts", "Voice control", "Expandable"],
    priceEGP: 1300, priceRange: "Low",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Security", "Automation"], sku: "TAPO-H200",
  },
  {
    id: "tapo-t110",
    name: "TP-Link Tapo T110 Door/Window Sensor",
    brand: "TP-Link Tapo", category: "Smart Sensors", subcategory: "Door/Window Sensor",
    protocol: "868MHz",
    description: "Compact door and window sensor — sends instant alerts when entries are opened. Works with Tapo Hub for full alarm integration.",
    features: ["Open/close alerts", "Tamper detection", "Long battery life", "Tapo Hub required", "App notifications"],
    priceEGP: 380, priceRange: "Low",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Security", "Automation"], sku: "TAPO-T110",
  },
  {
    id: "tapo-d230s1",
    name: "TP-Link Tapo D230S1 Battery Doorbell Kit",
    brand: "TP-Link Tapo", category: "Smart Doorbells", subcategory: "Battery Video Doorbell",
    protocol: "WiFi",
    description: "Wireless video doorbell kit — see who's at the door from anywhere. Comes with indoor chime and battery-powered camera.",
    features: ["2K video quality", "Wire-free battery", "Indoor chime included", "AI person detection", "2-way audio", "Night vision"],
    priceEGP: 2800, priceRange: "Medium",
    store: "Amazon.eg / Noon / B.TECH", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Security"], sku: "TAPO-D230S1",
  },

  // ── EZVIZ CAMERAS ─────────────────────────────────────────
  {
    id: "ezviz-c6n",
    name: "EZVIZ C6N 1080p Pan/Tilt Indoor Camera",
    brand: "EZVIZ", category: "Smart Cameras", subcategory: "Indoor Pan/Tilt Camera",
    protocol: "WiFi",
    description: "360° smart tracking indoor camera — follows movement automatically so you never miss what's happening in your home.",
    features: ["1080p Full HD", "360° pan/tilt", "Smart tracking", "Night vision", "2-way audio", "microSD up to 256GB"],
    priceEGP: 1555, priceRange: "Low",
    store: "Noon / Amazon.eg / Jumia / 2B Egypt", storeType: "Both", url: "https://noon.com/egypt-en",
    inStock: true, compatibility: ["Alexa", "Google Home", "IFTTT"],
    installation: "DIY", useCase: ["Security", "Baby Monitor"], sku: "EZVIZ-C6N", featured: true,
  },
  {
    id: "ezviz-c3n",
    name: "EZVIZ C3N Outdoor Color Night Vision Camera",
    brand: "EZVIZ", category: "Smart Cameras", subcategory: "Outdoor Camera",
    protocol: "WiFi",
    description: "Color night vision outdoor camera — captures full-color footage even in complete darkness. Smart light alarm deters intruders.",
    features: ["1080p outdoor", "Full color night vision", "IP67 weatherproof", "Motion detection", "2-way audio", "Smart light alarm"],
    priceEGP: 1400, priceRange: "Low",
    store: "Noon / Amazon.eg / 2B Egypt", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "IFTTT"],
    installation: "DIY", useCase: ["Security", "Outdoor"], sku: "EZVIZ-C3N",
  },
  {
    id: "ezviz-c8w-pro",
    name: "EZVIZ C8W Pro 2K Outdoor Pan/Tilt Camera",
    brand: "EZVIZ", category: "Smart Cameras", subcategory: "Outdoor Pan/Tilt Camera",
    protocol: "WiFi",
    description: "Flagship outdoor camera with 360° coverage, 2K resolution, and AI human/vehicle detection — complete exterior protection.",
    features: ["2K resolution", "360° outdoor pan/tilt", "Color night vision", "AI detection", "IP67", "Built-in spotlight"],
    priceEGP: 2800, priceRange: "Medium", badge: "Premium", badgeColor: "plasma",
    store: "Noon / Amazon.eg / Kimo Store", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "IFTTT"],
    installation: "DIY", useCase: ["Security", "Outdoor"], sku: "EZVIZ-C8W-PRO",
  },
  {
    id: "ezviz-cb3",
    name: "EZVIZ CS-CB3 Wire-Free Battery Outdoor Camera",
    brand: "EZVIZ", category: "Smart Cameras", subcategory: "Battery Camera",
    protocol: "WiFi",
    description: "Go wire-free outdoors — fully battery-powered camera with color night vision and AI detection. Mount anywhere in minutes.",
    features: ["Wire-free battery", "Color night vision", "IP65 weatherproof", "AI detection", "2-way audio", "Cloud + SD"],
    priceEGP: 2600, priceRange: "Medium",
    store: "Noon / Amazon.eg / Kimo Store", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Security", "Outdoor"], sku: "EZVIZ-CB3",
  },
  {
    id: "ezviz-dp2c",
    name: "EZVIZ CS-DP2C Peephole Camera Doorbell",
    brand: "EZVIZ", category: "Smart Doorbells", subcategory: "Peephole Doorbell Camera",
    protocol: "WiFi",
    description: "Replaces your existing door peephole with a smart camera — see, hear, and speak to visitors without opening the door.",
    features: ["Fits standard peepholes", "1080p full view", "Motion detection", "2-way audio", "Battery powered", "Night vision"],
    priceEGP: 2200, priceRange: "Medium",
    store: "Noon / Amazon.eg / Kimo Store", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "IFTTT"],
    installation: "DIY", useCase: ["Security"], sku: "EZVIZ-DP2C",
  },
  {
    id: "ezviz-h7c",
    name: "EZVIZ H7C 2K+ Indoor Pan/Tilt Camera",
    brand: "EZVIZ", category: "Smart Cameras", subcategory: "Indoor Pan/Tilt Camera",
    protocol: "WiFi",
    description: "Premium 2K+ indoor camera with AI body detection and sound alerts — enhanced evidence footage for full peace of mind.",
    features: ["2K+ resolution", "360° pan/tilt", "AI body detection", "Auto-tracking", "2-way audio", "Cloud + SD storage"],
    priceEGP: 1900, priceRange: "Medium",
    store: "Noon / Amazon.eg / Kimo Store", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "IFTTT"],
    installation: "DIY", useCase: ["Security", "Baby Monitor"], sku: "EZVIZ-H7C",
  },

  // ── GOVEE SMART LIGHTING ───────────────────────────────────
  {
    id: "govee-rgbic-5m",
    name: "Govee RGBIC LED Strip Lights 5m (WiFi)",
    brand: "Govee", category: "Smart Lighting", subcategory: "RGBIC LED Strip",
    protocol: "WiFi / Bluetooth",
    description: "Govee's stunning RGBIC strip — multiple colors simultaneously along the strip for next-level gaming setups, TV backlights, and room ambiance.",
    features: ["5m RGBIC strip", "16M colors simultaneously", "Music sync (built-in mic)", "Govee Home app", "Alexa & Google", "64+ scene modes"],
    priceEGP: 3999, priceRange: "Medium", badge: "Trending", badgeColor: "electric",
    store: "Amazon.eg / Games2Egypt / GamesworldEgypt", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Lighting", "Gaming", "Comfort"], sku: "GOVEE-RGBIC-5M", featured: true, isNew: true,
  },
  {
    id: "govee-neon-5m",
    name: "Govee Neon LED Rope Light 5m (WiFi + Matter)",
    brand: "Govee", category: "Smart Lighting", subcategory: "Neon Rope Light",
    protocol: "WiFi / Bluetooth / Matter",
    description: "Flexible neon-style RGB rope light that bends around any shape — desk edges, shelves, gaming setups. Matter certified for universal compatibility.",
    features: ["5m flexible neon", "RGBIC silicone diffuser", "Matter certified", "Music sync", "IP67 waterproof", "64+ scenes"],
    priceEGP: 5999, priceRange: "Medium", badge: "Matter Ready", badgeColor: "plasma",
    store: "Games2Egypt / Amazon.eg", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "SmartThings"],
    installation: "DIY", useCase: ["Lighting", "Gaming", "Comfort"], sku: "GOVEE-NEON-5M", isNew: true,
  },
  {
    id: "govee-tv-backlight-3-lite",
    name: "Govee TV Backlight 3 Lite (55-65\" TV)",
    brand: "Govee", category: "Smart Lighting", subcategory: "TV Backlight",
    protocol: "WiFi / Bluetooth",
    description: "Camera-synced TV backlight — automatically matches your screen colors for an immersive cinema experience at home.",
    features: ["Camera color sync", "RGBICW LED strip", "For 55-65\" TVs", "Music sync", "App + voice control", "4 colors in 1 bead"],
    priceEGP: 2699, priceRange: "Medium",
    store: "Amazon.eg / GamesworldEgypt", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Lighting", "Entertainment", "Comfort"], sku: "GOVEE-TV-BACKLIGHT-3LITE",
  },
  {
    id: "govee-rgbic-floor-lamp",
    name: "Govee RGBICWW Floor Lamp 2 (Matter)",
    brand: "Govee", category: "Smart Lighting", subcategory: "Smart Floor Lamp",
    protocol: "WiFi / Bluetooth / Matter",
    description: "Sleek floor lamp with full RGBICWW coloring and 1725 lumens — transforms any living room or bedroom corner into a design statement.",
    features: ["RGBICWW full spectrum", "1725 lumens", "Matter certified", "11 music modes", "80+ scenes", "App + voice control"],
    priceEGP: 11499, priceRange: "Premium",
    store: "GamesworldEgypt / Amazon.eg", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit"],
    installation: "DIY", useCase: ["Lighting", "Comfort", "Entertainment"], sku: "GOVEE-FLOOR-LAMP-2",
  },
  {
    id: "govee-glide-wall-lights",
    name: "Govee Glide RGBIC LED Wall Lights (6 pcs)",
    brand: "Govee", category: "Smart Lighting", subcategory: "Smart Wall Lights",
    protocol: "WiFi / Bluetooth",
    description: "Hexagon-style RGBIC wall light panels — create a stunning geometric light art installation on any wall. Perfect for gaming rooms and living areas.",
    features: ["6-piece set", "RGBIC 57 colors at once", "Music sync", "App + voice control", "Modular/expandable", "Alexa & Google"],
    priceEGP: 3799, priceRange: "Medium",
    store: "GamesworldEgypt / Amazon.eg", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Lighting", "Gaming", "Comfort"], sku: "GOVEE-GLIDE-WALL",
  },
  {
    id: "govee-m1-strip-matter",
    name: "Govee M1 LED Strip Light 5m (Matter)",
    brand: "Govee", category: "Smart Lighting", subcategory: "RGBIC LED Strip",
    protocol: "WiFi / Bluetooth / Matter",
    description: "Govee's first Matter-certified strip light — integrates directly with Apple Home, Google Home, Alexa, and SmartThings without extra setup.",
    features: ["5m RGBIC strip", "Matter certified", "4-in-1 RGBICW chip", "60 LEDs/m", "20 customizable segments", "All platforms"],
    priceEGP: 1799, priceRange: "Low", badge: "Matter", badgeColor: "electric",
    store: "GamesworldEgypt / Amazon.eg", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "SmartThings"],
    installation: "DIY", useCase: ["Lighting", "Gaming", "Comfort"], sku: "GOVEE-M1-MATTER", isNew: true,
  },

  // ── AQARA ──────────────────────────────────────────────────
  {
    id: "aqara-hub-m2",
    name: "Aqara Hub M2 Smart Home Bridge",
    brand: "Aqara", category: "Gateways & Hubs", subcategory: "Zigbee Hub",
    protocol: "Zigbee / WiFi",
    description: "Aqara's flagship hub — connects up to 128 Zigbee devices, built-in IR blaster for AC control, and native Apple HomeKit integration.",
    features: ["128 Zigbee devices", "Built-in IR remote", "Apple HomeKit native", "Alexa & Google", "Local processing", "IFTTT support"],
    priceEGP: 1800, priceRange: "Medium",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://noon.com/egypt-en",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "Home Assistant"],
    installation: "DIY", useCase: ["Automation"], sku: "AQARA-HUB-M2",
  },
  {
    id: "aqara-lock-u200",
    name: "Aqara Smart Lock U200 (Matter + HomeKit)",
    brand: "Aqara", category: "Smart Locks", subcategory: "Matter Smart Lock",
    protocol: "Zigbee / Matter",
    description: "Premium smart lock with Apple Home Key — unlock with iPhone or Apple Watch. Fingerprint, code, card, and app access all supported.",
    features: ["Apple Home Key", "Fingerprint unlock", "Matter certified", "Code + NFC card", "Auto-lock", "Access history"],
    priceEGP: 19516, priceRange: "Premium", badge: "Apple HomeKey", badgeColor: "plasma",
    store: "Amazon.eg", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "SmartThings"],
    installation: "Technician", useCase: ["Security"], sku: "AQARA-U200",
  },
  {
    id: "aqara-h1-nn",
    name: "Aqara Wall Switch H1 Zigbee (No Neutral)",
    brand: "Aqara", category: "Smart Switches", subcategory: "Zigbee Wall Switch",
    protocol: "Zigbee",
    description: "Elegant glass wall switch for older homes with no neutral wire — instantly smartens your lights with Zigbee reliability and Apple HomeKit.",
    features: ["No neutral required", "Zigbee 3.0", "Glass panel", "HomeKit native", "Hub required", "Alexa & Google"],
    priceEGP: 2200, priceRange: "Medium",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "Home Assistant"],
    installation: "Electrician", useCase: ["Lighting", "Automation"], sku: "AQARA-H1-NN",
  },
  {
    id: "aqara-cube-t1",
    name: "Aqara Cube T1 Pro Smart Controller",
    brand: "Aqara", category: "Smart Sensors", subcategory: "Gesture Controller",
    protocol: "Zigbee",
    description: "Unique cube controller — shake, rotate, flip, or tap it to trigger any automation. A conversation piece and genuinely useful tool.",
    features: ["6 gesture actions", "Rotate / shake / flip", "Zigbee 3.0", "HomeKit / Alexa / Google", "Hub required", "Rechargeable"],
    priceEGP: 1600, priceRange: "Medium",
    store: "Amazon.eg", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "Home Assistant"],
    installation: "DIY", useCase: ["Automation"], sku: "AQARA-CUBE-T1",
  },
  {
    id: "aqara-ms-p1",
    name: "Aqara Motion Sensor P1 Zigbee",
    brand: "Aqara", category: "Smart Sensors", subcategory: "Motion Sensor",
    protocol: "Zigbee",
    description: "High-precision motion sensor with adjustable detection sensitivity — perfect for security automation and hands-free lighting.",
    features: ["Wide FOV detection", "Adjustable sensitivity", "5-year battery", "Zigbee 3.0", "HomeKit / Alexa / Google"],
    priceEGP: 1100, priceRange: "Low",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "Home Assistant"],
    installation: "DIY", useCase: ["Security", "Automation"], sku: "AQARA-MS-P1",
  },

  // ── LEZN SMART LOCKS ───────────────────────────────────────
  {
    id: "lezn-k30-face",
    name: "LEZN K30 Face Recognition Smart Lock",
    brand: "LEZN", category: "Smart Locks", subcategory: "Face Recognition Lock",
    protocol: "WiFi / Bluetooth",
    description: "3D face recognition smart lock — unlocks in 0.3 seconds by recognizing your face even in the dark. 6 access methods in one sleek device.",
    features: ["3D face recognition", "Fingerprint unlock", "PIN + NFC card", "App remote unlock", "Visitor time-codes", "Tuya app", "Access history"],
    priceEGP: 19500, priceRange: "Premium", badge: "Face ID", badgeColor: "electric",
    store: "ASG Smart Egypt", storeType: "Both", url: "https://asg.com.eg",
    inStock: true, compatibility: ["Tuya", "Smart Life", "Alexa", "Google Home"],
    installation: "Technician", useCase: ["Security"], sku: "LEZN-K30-FACE", featured: true, isNew: true,
  },
  {
    id: "lezn-r02-cateye",
    name: "LEZN R02 Cat Eye Video Smart Lock",
    brand: "LEZN", category: "Smart Locks", subcategory: "Video Smart Lock",
    protocol: "WiFi / Bluetooth",
    description: "Smart lock with built-in wide-angle cat eye camera — see who's at the door, speak to them, and unlock remotely from your phone.",
    features: ["Built-in video camera", "Wide-angle view", "2-way audio", "PIN code access", "App remote unlock", "WiFi 2.4G Tuya"],
    priceEGP: 14500, priceRange: "Premium", badge: "Video Lock", badgeColor: "plasma",
    store: "ASG Smart Egypt", storeType: "Both", url: "https://asg.com.eg",
    inStock: true, compatibility: ["Tuya", "Smart Life", "Alexa", "Google Home"],
    installation: "Technician", useCase: ["Security"], sku: "LEZN-R02-CATEYE", isNew: true,
  },
  {
    id: "lezn-r03-cateye",
    name: "LEZN R03 Cat Eye Premium Video Lock",
    brand: "LEZN", category: "Smart Locks", subcategory: "Video Smart Lock",
    protocol: "WiFi / Bluetooth",
    description: "Premium cat eye video lock with fingerprint access and high-res camera — ideal for Airbnb properties and modern Egyptian apartments.",
    features: ["High-res cat eye camera", "Fingerprint access", "Video preview", "Remote app unlock", "Time-limited guest codes", "Tuya app"],
    priceEGP: 16500, priceRange: "Premium",
    store: "ASG Smart Egypt", storeType: "Both", url: "https://asg.com.eg",
    inStock: true, compatibility: ["Tuya", "Smart Life", "Alexa", "Google Home"],
    installation: "Technician", useCase: ["Security"], sku: "LEZN-R03-CATEYE",
  },
  {
    id: "lezn-i12",
    name: "LEZN i12 Face + Video Intercom Smart Lock",
    brand: "LEZN", category: "Smart Locks", subcategory: "Intercom Smart Lock",
    protocol: "WiFi / Bluetooth",
    description: "Ultimate combination — face recognition, video calling, fingerprint, and touch access. The most feature-rich smart lock available in Egypt.",
    features: ["Face recognition", "Video intercom calling", "Fingerprint + PIN", "NFC card", "Remote unlock", "Auto light in dark", "Tuya app"],
    priceEGP: 22000, priceRange: "Premium", badge: "Ultimate", badgeColor: "aurora",
    store: "ASG Smart Egypt", storeType: "Both", url: "https://asg.com.eg",
    inStock: true, compatibility: ["Tuya", "Smart Life", "Alexa", "Google Home"],
    installation: "Technician", useCase: ["Security"], sku: "LEZN-I12", isNew: true,
  },
  {
    id: "lezn-k1",
    name: "LEZN K1 Smart Lock (Fingerprint + Tuya)",
    brand: "LEZN", category: "Smart Locks", subcategory: "Fingerprint Smart Lock",
    protocol: "WiFi / Bluetooth",
    description: "Modern keyless entry with fingerprint and Tuya app access — sleek, powerful, and the perfect upgrade for any Egyptian door.",
    features: ["Fingerprint unlock", "Tuya app control", "PIN code", "Physical key backup", "Low battery alert", "Access log"],
    priceEGP: 8500, priceRange: "Medium",
    store: "ASG Smart Egypt", storeType: "Both", url: "https://asg.com.eg",
    inStock: true, compatibility: ["Tuya", "Smart Life"],
    installation: "Technician", useCase: ["Security"], sku: "LEZN-K1",
  },
  {
    id: "lezn-r8",
    name: "LEZN R8 Budget Smart Lock",
    brand: "LEZN", category: "Smart Locks", subcategory: "Fingerprint Smart Lock",
    protocol: "Bluetooth",
    description: "Entry-level smart security — keyless fingerprint access with app control. The most affordable way to upgrade your door security.",
    features: ["Fingerprint reader", "Bluetooth app", "PIN code", "Physical key", "Low battery alert"],
    priceEGP: 5500, priceRange: "Medium",
    store: "ASG Smart Egypt", storeType: "Both", url: "https://asg.com.eg",
    inStock: true, compatibility: ["Tuya", "Smart Life"],
    installation: "Technician", useCase: ["Security"], sku: "LEZN-R8",
  },

  // ── PANDA SMART LOCKS ─────────────────────────────────────
  {
    id: "panda-i17",
    name: "PNDA i17 Face ID + Video Intercom Lock",
    brand: "PANDA", category: "Smart Locks", subcategory: "Face Recognition Lock",
    protocol: "WiFi / Bluetooth",
    description: "Combines face recognition, video intercom, and fingerprint in one sleek lock — perfect for secure modern living in Egyptian compounds.",
    features: ["Face ID unlock", "Video intercom", "Fingerprint + PIN", "NFC card", "App remote unlock", "Tuya app", "Multi-admin"],
    priceEGP: 18000, priceRange: "Premium",
    store: "ASG Smart Egypt", storeType: "Both", url: "https://asg.com.eg",
    inStock: true, compatibility: ["Tuya", "Smart Life", "Alexa", "Google Home"],
    installation: "Technician", useCase: ["Security"], sku: "PANDA-I17", isNew: true,
  },
  {
    id: "panda-i18",
    name: "PANDA i18 6-Method Access Smart Lock",
    brand: "PANDA", category: "Smart Locks", subcategory: "Fingerprint Smart Lock",
    protocol: "WiFi / Bluetooth",
    description: "6 ways to enter: face, fingerprint, app, PIN, card, and key. Ideal for rental properties and families needing flexible access management.",
    features: ["6 unlock methods", "Face recognition", "Fingerprint", "Tuya app", "PIN + NFC card", "Physical key", "Multi-lock management"],
    priceEGP: 15000, priceRange: "Premium",
    store: "ASG Smart Egypt", storeType: "Both", url: "https://asg.com.eg",
    inStock: true, compatibility: ["Tuya", "Smart Life", "Alexa", "Google Home"],
    installation: "Technician", useCase: ["Security"], sku: "PANDA-I18",
  },
  {
    id: "philips-ddl608",
    name: "Philips DDL608 Fingerprint Smart Lock",
    brand: "PANDA", category: "Smart Locks", subcategory: "Fingerprint Smart Lock",
    protocol: "WiFi / Bluetooth",
    description: "Narrow-profile Philips smart lock with fingerprint, PIN, RFID, and app access — perfect for slim Egyptian doors.",
    features: ["Fingerprint + PIN", "RFID card", "App control", "Narrow body design", "Weather-resistant", "Push-lever handle"],
    priceEGP: 9500, priceRange: "Medium",
    store: "ASG Smart Egypt", storeType: "Both", url: "https://asg.com.eg",
    inStock: true, compatibility: ["Tuya", "Smart Life"],
    installation: "Technician", useCase: ["Security"], sku: "PHILIPS-DDL608",
  },

  // ── VIDEO INTERCOM ─────────────────────────────────────────
  {
    id: "hikvision-intercom-ds-kis202t",
    name: "Hikvision DS-KIS202T Video Intercom Kit",
    brand: "Hikvision", category: "Video Intercom", subcategory: "Wired Video Intercom",
    protocol: "Wired / IP",
    description: "Professional wired video intercom with 7\" TFT touch screen — crystal-clear 1080p outdoor camera and noise-cancelling two-way audio.",
    features: ["7\" TFT LCD touchscreen", "1080p outdoor camera", "Built-in mic & speaker", "Noise echo cancellation", "Door release", "Night vision"],
    priceEGP: 5700, priceRange: "Medium", badge: "Professional", badgeColor: "electric",
    store: "Amazon.eg / Noon / B.TECH", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Hik-Connect", "Hikvision iVMS"],
    installation: "Technician", useCase: ["Security"], sku: "HIK-DS-KIS202T", featured: true,
  },
  {
    id: "commax-video-intercom-7",
    name: "Commax CDV-70MHD Video Door Phone (7\")",
    brand: "Commax", category: "Video Intercom", subcategory: "Wired Video Intercom",
    protocol: "Wired",
    description: "Korea's most trusted intercom brand — 7\" color display with one-touch door release, crisp camera, and reliable day/night vision.",
    features: ["7\" color monitor", "1 outdoor unit", "One-touch door release", "Night vision camera", "Multi-apartment support", "High-quality audio"],
    priceEGP: 6900, priceRange: "Medium",
    store: "Amazon.eg / Noon / B.TECH / Raya Shop", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Commax App (select models)"],
    installation: "Technician", useCase: ["Security"], sku: "COMMAX-CDV70MHD",
  },
  {
    id: "tuya-video-intercom-7",
    name: "Tuya WiFi Video Intercom System (7\" Touch)",
    brand: "Tuya", category: "Video Intercom", subcategory: "WiFi Video Intercom",
    protocol: "WiFi",
    description: "Smart WiFi video intercom — answer the door from your phone anywhere in the world. 7\" touchscreen indoor monitor with outdoor camera.",
    features: ["7\" color touch screen", "1080p outdoor camera", "WiFi app control", "Remote unlock", "IR night vision", "120° wide angle", "Tuya / Smart Life"],
    priceEGP: 3800, priceRange: "Medium", badge: "Smart WiFi", badgeColor: "aurora",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Tuya", "Smart Life", "Alexa", "Google Home"],
    installation: "Technician", useCase: ["Security"], sku: "TUYA-INTERCOM-7", isNew: true,
  },
  {
    id: "ezviz-hp7-intercom",
    name: "EZVIZ HP7 WiFi 2K Video Doorbell + 7\" Monitor",
    brand: "EZVIZ", category: "Video Intercom", subcategory: "WiFi Smart Intercom",
    protocol: "WiFi",
    description: "Premium WiFi intercom system — 2K doorbell camera connects wirelessly to a 7\" indoor touch monitor with person detection.",
    features: ["2K outdoor camera", "7\" indoor touchscreen", "Person detection", "2-way audio", "Door opener", "Dual-band WiFi", "Cloud + SD"],
    priceEGP: 7200, priceRange: "Medium", badge: "2K Smart", badgeColor: "plasma",
    store: "Amazon.eg / Noon / Kimo Store", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "EZVIZ app"],
    installation: "Technician", useCase: ["Security"], sku: "EZVIZ-HP7", isNew: true,
  },
  {
    id: "akuvox-r20a",
    name: "Akuvox R20A SIP Video Door Phone",
    brand: "Akuvox", category: "Video Intercom", subcategory: "SIP IP Intercom",
    protocol: "SIP / IP",
    description: "Professional SIP video doorphone for apartments and offices — compact, PoE-powered, and integrates with professional access control systems.",
    features: ["SIP video door phone", "PoE powered", "Mobile access", "Real-time video", "Access control integration", "3.5\" display"],
    priceEGP: 4500, priceRange: "Medium",
    store: "VoIP Egypt / Professional Dealers", storeType: "Both", url: "https://voipegypt.me",
    inStock: true, compatibility: ["SIP / ONVIF", "Home Assistant"],
    installation: "Technician", useCase: ["Security"], sku: "AKUVOX-R20A",
  },

  // ── SMART STAIRCASE LIGHTING (PIANO STAIRS) ────────────────
  {
    id: "smart-stairs-kit-16step",
    name: "Smart Piano Staircase LED Kit (16 Steps, RGB + Motion)",
    brand: "Tuya", category: "Staircase Lighting", subcategory: "Smart Staircase Kit",
    protocol: "WiFi / Bluetooth",
    description: "Transform your staircase into a living light show — LEDs cascade step-by-step as you walk up or down. Motion sensors trigger the piano stair wave effect automatically.",
    features: ["16 LED step lights", "PIR motion sensors (top + bottom)", "RGB color changing", "Waterfall/wave effect", "WiFi app control", "Alexa & Google", "Tuya app", "Adjustable brightness & timing"],
    priceEGP: 4500, priceRange: "Medium", badge: "Piano Stairs", badgeColor: "electric",
    store: "Amazon.eg / Noon / Specialty Smart Home Stores", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Tuya", "Smart Life"],
    installation: "DIY", useCase: ["Lighting", "Comfort", "Safety"], sku: "STAIRS-RGB-16", featured: true, isNew: true,
  },
  {
    id: "smart-stairs-kit-cob-20step",
    name: "Smart Staircase COB LED Kit (20 Steps, Warm White)",
    brand: "Tuya", category: "Staircase Lighting", subcategory: "Smart Staircase Kit",
    protocol: "WiFi",
    description: "Dotless COB LED stair lighting kit — smooth, elegant warm white illumination cascades step-by-step when motion is detected. Premium diffused glow.",
    features: ["20 COB LED strips", "Dotless smooth light", "Warm white 3000K", "Dual motion sensors", "Tuya WiFi control", "Adjustable timing 10s-3min", "Dimming control"],
    priceEGP: 5800, priceRange: "Medium",
    store: "Amazon.eg / Specialty LED Stores", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Tuya", "Smart Life", "Alexa", "Google Home"],
    installation: "DIY", useCase: ["Lighting", "Safety", "Comfort"], sku: "STAIRS-COB-20",
  },
  {
    id: "smart-stairs-rgbic-12step",
    name: "Smart Piano Staircase RGBIC Kit (12 Steps, App Control)",
    brand: "Tuya", category: "Staircase Lighting", subcategory: "Smart Staircase Kit",
    protocol: "WiFi / Bluetooth",
    description: "12-step RGBIC staircase lighting with individual step color control — create patterns, rainbows, and wave effects. App-controlled with 64+ scene modes.",
    features: ["12 RGBIC step strips", "Individual color per step", "64+ scene modes", "Music sync", "PIR motion sensors", "Bluetooth + WiFi", "Alexa & Google"],
    priceEGP: 3800, priceRange: "Medium", badge: "RGBIC Magic", badgeColor: "plasma",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Tuya"],
    installation: "DIY", useCase: ["Lighting", "Safety", "Comfort"], sku: "STAIRS-RGBIC-12",
  },
  {
    id: "smart-stairs-controller-s19",
    name: "Smart LED Staircase Controller with 20 Outputs",
    brand: "Tuya", category: "Staircase Lighting", subcategory: "Staircase Controller",
    protocol: "WiFi",
    description: "The brain of any smart staircase — controls up to 20 LED step outputs with wave effects, bidirectional motion detection, and app-configurable timing.",
    features: ["20 step outputs", "Bidirectional motion sensors", "Wave/waterfall effect", "Standby mode with dim", "WiFi app control", "Timing 0.25s-5s adjustable", "Day/night mode"],
    priceEGP: 2200, priceRange: "Medium",
    store: "Amazon.eg / LED Specialty Stores", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Tuya", "Smart Life"],
    installation: "DIY", useCase: ["Lighting", "Safety"], sku: "STAIRS-CTRL-20",
  },

  // ── FIBARO (Z-Wave Premium) ────────────────────────────────
  {
    id: "fibaro-home-center-3",
    name: "Fibaro Home Center 3 (Z-Wave Hub)",
    brand: "Fibaro", category: "Gateways & Hubs", subcategory: "Z-Wave Premium Hub",
    protocol: "Z-Wave / Zigbee / WiFi",
    description: "Europe's most powerful smart home hub — fully local processing, 230 device support, and the most comprehensive automation rules engine in the market.",
    features: ["Z-Wave + Zigbee + WiFi", "230+ devices", "Local processing", "Advanced scenes", "Alexa / Google / HomeKit", "IFTTT", "Energy monitoring"],
    priceEGP: 38000, priceRange: "Premium", badge: "Professional Grade", badgeColor: "plasma",
    store: "Amazon.eg / Stebilex Egypt", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "Home Assistant", "IFTTT"],
    installation: "Technician", useCase: ["Automation", "Security", "Energy", "Climate"], sku: "FIBARO-HC3",
  },
  {
    id: "fibaro-dimmer-2",
    name: "Fibaro Dimmer 2 (Z-Wave Smart Dimmer)",
    brand: "Fibaro", category: "Smart Switches", subcategory: "Z-Wave Dimmer Module",
    protocol: "Z-Wave",
    description: "World's smallest dimmer module — fits behind any wall switch and supports any type of light source including LED, CFL, and halogen.",
    features: ["Z-Wave dimmer module", "50W-500W", "Soft-start protection", "Overload protection", "Scenes support", "Energy monitoring"],
    priceEGP: 4500, priceRange: "Medium",
    store: "Amazon.eg / Stebilex Egypt", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "Home Assistant"],
    installation: "Electrician", useCase: ["Lighting", "Automation"], sku: "FIBARO-DIMMER2",
  },
  {
    id: "fibaro-door-sensor",
    name: "Fibaro Door/Window Sensor 2 (Z-Wave, Magnetic)",
    brand: "Fibaro", category: "Smart Sensors", subcategory: "Z-Wave Door/Window Sensor",
    protocol: "Z-Wave",
    description: "Nature-inspired smart sensor — detects when doors or windows open and closes with temperature monitoring built in. Award-winning design.",
    features: ["Z-Wave Plus", "Built-in temperature sensor", "External sensor input", "Tamper detection", "5-year battery", "IP44 weather resistant"],
    priceEGP: 3200, priceRange: "Medium",
    store: "Amazon.eg / Stebilex Egypt / B.TECH", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "Home Assistant"],
    installation: "DIY", useCase: ["Security", "Automation", "Climate"], sku: "FIBARO-DWS2",
  },
  {
    id: "fibaro-motion-sensor",
    name: "Fibaro Motion Sensor (Z-Wave, Eye Design)",
    brand: "Fibaro", category: "Smart Sensors", subcategory: "Z-Wave Motion Sensor",
    protocol: "Z-Wave",
    description: "The iconic cat's eye motion sensor — detects movement, temperature, light level, and vibration all in one ultra-compact sphere.",
    features: ["Z-Wave Plus", "PIR motion detection", "Temperature sensor", "Light sensor", "Vibration sensor", "Built-in accelerometer", "5-year battery"],
    priceEGP: 4200, priceRange: "Medium", badge: "Award Winning", badgeColor: "aurora",
    store: "Amazon.eg / Stebilex Egypt", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "Home Assistant"],
    installation: "DIY", useCase: ["Security", "Automation", "Climate"], sku: "FIBARO-MS",
  },
  {
    id: "fibaro-smart-implant",
    name: "Fibaro Smart Implant (Universal Z-Wave Module)",
    brand: "Fibaro", category: "Smart Switches", subcategory: "Z-Wave Universal Module",
    protocol: "Z-Wave",
    description: "Universal smart module that makes ANY device smart — connect gates, garage doors, irrigation systems, or industrial equipment to your smart home.",
    features: ["2 digital inputs", "2 analog inputs", "2 relay outputs", "Gate/garage control", "Temperature sensors", "Z-Wave Plus"],
    priceEGP: 3800, priceRange: "Medium",
    store: "Amazon.eg / Stebilex Egypt", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "Home Assistant"],
    installation: "Technician", useCase: ["Automation", "Security"], sku: "FIBARO-IMPLANT",
  },

  // ── HDL AUTOMATION ─────────────────────────────────────────
  {
    id: "hdl-buspro-controller",
    name: "HDL Buspro Smart Home Controller",
    brand: "HDL", category: "Gateways & Hubs", subcategory: "Professional Automation Hub",
    protocol: "HDL Bus / IP",
    description: "Professional building automation hub — controls lighting, HVAC, curtains, AV systems, and security from one unified system for villas and hotels.",
    features: ["HDL Bus protocol", "Lighting control", "HVAC integration", "Curtain control", "AV system control", "Security integration", "Touch panel support"],
    priceEGP: 15000, priceRange: "Premium", badge: "Pro Install", badgeColor: "plasma",
    store: "HDL Egypt / Professional Dealers", storeType: "Both", url: "https://hdlegypt.com",
    inStock: true, compatibility: ["HDL App", "Alexa", "Google Home", "KNX Gateway"],
    installation: "Technician", useCase: ["Automation", "Energy", "Lighting", "Climate", "Security"], sku: "HDL-BUSPRO-CTRL",
  },
  {
    id: "hdl-touch-panel-4",
    name: "HDL 4-Button Smart Touch Panel",
    brand: "HDL", category: "Control Panels", subcategory: "Wired Touch Panel",
    protocol: "HDL Bus",
    description: "Elegant 4-button HDL touch panel — controls lighting scenes, curtains, and HVAC from a premium glass panel. Used in Dubai Airport and luxury hotels.",
    features: ["4 programmable buttons", "Glass surface", "LED indicators", "Scene activation", "HDL Bus wired", "Custom labels", "Dimmer compatible"],
    priceEGP: 8500, priceRange: "Premium",
    store: "HDL Egypt / Professional Dealers", storeType: "Both", url: "https://hdlegypt.com",
    inStock: true, compatibility: ["HDL App", "Alexa", "Google Home"],
    installation: "Technician", useCase: ["Lighting", "Climate", "Automation"], sku: "HDL-TOUCH-4B",
  },
  {
    id: "hdl-12ch-dimmer",
    name: "HDL 12-Channel LED Dimmer Module",
    brand: "HDL", category: "Smart Switches", subcategory: "Professional Dimmer Module",
    protocol: "HDL Bus",
    description: "Professional 12-channel LED dimmer for hotels and villas — controls 12 independent lighting circuits from one DIN-rail module.",
    features: ["12 independent channels", "0-100% dimming", "DIN rail mount", "HDL Bus", "0-10V output", "Overload protection", "Scene memory"],
    priceEGP: 18000, priceRange: "Premium",
    store: "HDL Egypt / Professional Dealers", storeType: "Both", url: "https://hdlegypt.com",
    inStock: true, compatibility: ["HDL App", "Alexa", "Google Home"],
    installation: "Technician", useCase: ["Lighting", "Automation"], sku: "HDL-12CH-DIMMER",
  },
  {
    id: "hdl-floor-heating",
    name: "HDL Floor Heating Thermostat Controller",
    brand: "HDL", category: "Smart Climate", subcategory: "Professional Thermostat",
    protocol: "HDL Bus",
    description: "Precise floor heating control for luxury Egyptian projects — manages in-floor heating with intelligent scheduling and remote control.",
    features: ["Floor heating control", "Weekly scheduling", "Intelligent modes", "HDL Bus", "Touch display", "Energy optimization"],
    priceEGP: 6500, priceRange: "Premium",
    store: "HDL Egypt / Professional Dealers", storeType: "Both", url: "https://hdlegypt.com",
    inStock: true, compatibility: ["HDL App"],
    installation: "Technician", useCase: ["Climate", "Energy Saving", "Comfort"], sku: "HDL-FLOOR-THERMO",
  },

  // ── ALEXA CONTROL SCREENS ─────────────────────────────────
  {
    id: "amazon-echo-show-5",
    name: "Amazon Echo Show 5 (Smart Display + Hub)",
    brand: "Amazon", category: "Control Panels", subcategory: "Smart Display",
    protocol: "WiFi / Zigbee / Bluetooth",
    description: "Compact 5.5\" smart display that becomes your home's visual control center — view cameras, control devices, and ask Alexa anything with a tap or voice.",
    features: ["5.5\" touchscreen", "Alexa built-in", "Camera viewing", "Smart home dashboard", "Video calls", "Smart home hub", "Zigbee compatible"],
    priceEGP: 2500, priceRange: "Medium", badge: "Alexa Screen", badgeColor: "electric",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Zigbee", "Matter"],
    installation: "DIY", useCase: ["Automation", "Security", "Entertainment", "Comfort"], sku: "ECHO-SHOW-5", featured: true,
  },
  {
    id: "amazon-echo-show-8",
    name: "Amazon Echo Show 8 (2nd Gen Smart Display)",
    brand: "Amazon", category: "Control Panels", subcategory: "Smart Display",
    protocol: "WiFi / Zigbee / Bluetooth",
    description: "8\" HD smart display with adaptive color — the perfect kitchen or living room smart home controller and entertainment hub.",
    features: ["8\" HD touchscreen", "Adaptive color display", "Camera for video calls", "Smart home hub", "Alexa built-in", "Music + entertainment"],
    priceEGP: 3800, priceRange: "Medium",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Zigbee", "Matter"],
    installation: "DIY", useCase: ["Automation", "Entertainment", "Security"], sku: "ECHO-SHOW-8",
  },
  {
    id: "amazon-echo-show-10",
    name: "Amazon Echo Show 10 (Rotating 10.1\" Display)",
    brand: "Amazon", category: "Control Panels", subcategory: "Smart Display",
    protocol: "WiFi / Zigbee / Bluetooth",
    description: "10.1\" smart display that follows you around the room — rotates automatically to face you. The ultimate Alexa smart home control screen.",
    features: ["10.1\" HD display", "Auto-rotating motor", "13MP wide camera", "Smart home hub", "Alexa built-in", "Matter + Thread support"],
    priceEGP: 8500, priceRange: "Premium", badge: "Flagship", badgeColor: "aurora",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Zigbee", "Matter", "Thread"],
    installation: "DIY", useCase: ["Automation", "Entertainment", "Security"], sku: "ECHO-SHOW-10",
  },
  {
    id: "amazon-echo-dot-5",
    name: "Amazon Echo Dot 5th Gen (Smart Speaker)",
    brand: "Amazon", category: "Smart Audio", subcategory: "Smart Speaker",
    protocol: "WiFi / Bluetooth",
    description: "Compact smart speaker that acts as your voice-controlled smart home hub — control lights, plugs, cameras, and more with your voice.",
    features: ["Alexa built-in", "360° audio", "Smart home hub", "Music streaming", "Calls & timer", "Matter support"],
    priceEGP: 1800, priceRange: "Low",
    store: "Amazon.eg / Noon / Jumia", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Matter"],
    installation: "DIY", useCase: ["Automation", "Comfort"], sku: "ECHO-DOT-5",
  },
  {
    id: "amazon-echo-4-hub",
    name: "Amazon Echo (4th Gen) with Zigbee Hub",
    brand: "Amazon", category: "Control Panels", subcategory: "Smart Speaker Hub",
    protocol: "WiFi / Zigbee / Bluetooth",
    description: "Amazon's premium speaker with built-in Zigbee hub — control all Alexa-compatible devices without needing a separate bridge.",
    features: ["Built-in Zigbee hub", "Alexa smart home center", "Premium 360° audio", "Matter support", "Thread border router", "Eero WiFi mesh"],
    priceEGP: 3200, priceRange: "Medium",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Zigbee", "Matter", "Thread"],
    installation: "DIY", useCase: ["Automation", "Entertainment"], sku: "ECHO-4TH-HUB",
  },

  // ── GOOGLE CONTROL SCREENS ────────────────────────────────
  {
    id: "google-nest-hub-2",
    name: "Google Nest Hub 2nd Gen (7\" Smart Display)",
    brand: "Google", category: "Control Panels", subcategory: "Smart Display",
    protocol: "WiFi / Bluetooth",
    description: "7\" Google smart display — control your entire smart home with touch or voice, view cameras, and get sleep tracking insights on your bedside table.",
    features: ["7\" touchscreen", "Google Assistant", "Camera viewing", "Sleep tracking sensor", "Smart home dashboard", "Photo frame mode"],
    priceEGP: 2800, priceRange: "Medium", badge: "Google Screen", badgeColor: "aurora",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Google Home", "Matter", "Thread"],
    installation: "DIY", useCase: ["Automation", "Entertainment", "Comfort"], sku: "NEST-HUB-2", featured: true,
  },
  {
    id: "google-nest-hub-max",
    name: "Google Nest Hub Max (10\" Large Display)",
    brand: "Google", category: "Control Panels", subcategory: "Smart Display",
    protocol: "WiFi / Bluetooth",
    description: "10\" Google smart display with built-in camera — see your doorbell camera feed, make video calls, and control your home with one large screen.",
    features: ["10\" HD touchscreen", "Built-in camera", "Face Match recognition", "Nest camera integration", "Google Assistant", "Premium audio"],
    priceEGP: 6500, priceRange: "Premium",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Google Home", "Matter", "Thread"],
    installation: "DIY", useCase: ["Automation", "Entertainment", "Security"], sku: "NEST-HUB-MAX",
  },
  {
    id: "google-nest-mini-2",
    name: "Google Nest Mini 2nd Gen (Smart Speaker)",
    brand: "Google", category: "Smart Audio", subcategory: "Smart Speaker",
    protocol: "WiFi / Bluetooth",
    description: "Small but powerful Google smart speaker — control your entire smart home with voice commands and get instant Google answers.",
    features: ["Google Assistant", "360° sound", "Google Home hub", "Music & routines", "Voice Match", "Privacy mute"],
    priceEGP: 1500, priceRange: "Low",
    store: "Amazon.eg / Noon / Jumia", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Google Home", "Matter"],
    installation: "DIY", useCase: ["Automation", "Comfort", "Entertainment"], sku: "GOOGLE-NEST-MINI-2",
  },

  // ── TUYA PRODUCTS ─────────────────────────────────────────
  {
    id: "tuya-switch-3g-glass",
    name: "Tuya WiFi 3-Gang Glass Touch Switch",
    brand: "Tuya", category: "Smart Switches", subcategory: "WiFi Touch Wall Switch",
    protocol: "WiFi",
    description: "Affordable 3-gang glass touch switch — works with Smart Life app, Alexa, and Google. The most budget-friendly way to go smart in Egypt.",
    features: ["3-gang glass panel", "Smart Life app", "Alexa & Google Home", "Timer & schedule", "Remote control"],
    priceEGP: 750, priceRange: "Low",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Tuya"],
    installation: "Electrician", useCase: ["Lighting", "Automation"], sku: "TUYA-SWITCH-3G",
  },
  {
    id: "tuya-plug-20a",
    name: "Tuya WiFi Smart Plug 20A (with Energy Monitor)",
    brand: "Tuya", category: "Smart Plugs", subcategory: "Heavy-Duty WiFi Plug",
    protocol: "WiFi",
    description: "Heavy-duty 20A smart plug with energy monitoring — control air conditioners, heaters, and other high-draw Egyptian appliances smartly.",
    features: ["20A / 4400W", "Energy monitoring", "Timer & countdown", "Smart Life app", "Alexa & Google", "Overload protection"],
    priceEGP: 999, priceRange: "Low",
    store: "Amazon.eg / Noon / Aura Smart Home", storeType: "Online", url: "https://aura.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Tuya"],
    installation: "DIY", useCase: ["Energy Saving", "Automation"], sku: "TUYA-PLUG-20A",
  },
  {
    id: "tuya-ir-blaster",
    name: "Tuya WiFi IR Blaster (Universal AC Remote)",
    brand: "Tuya", category: "Smart Climate", subcategory: "Universal IR Remote",
    protocol: "WiFi / IR",
    description: "Control your AC, TV, and any IR device from your phone — convert any legacy appliance into a smart device instantly. Essential for Egypt's hot climate.",
    features: ["Supports AC, TV, fan, etc.", "Smart Life app", "IR + RF control", "Auto-learn any remote", "Alexa & Google"],
    priceEGP: 550, priceRange: "Low", badge: "AC Control", badgeColor: "electric",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Tuya"],
    installation: "DIY", useCase: ["Climate", "Automation", "Comfort"], sku: "TUYA-IR-BLASTER", featured: true,
  },
  {
    id: "tuya-curtain-rod",
    name: "Tuya WiFi Curtain Motor (Rod Type)",
    brand: "Tuya", category: "Smart Curtains", subcategory: "WiFi Curtain Motor",
    protocol: "WiFi",
    description: "Rod-type smart curtain motor — silently opens and closes your curtains on a schedule or voice command. DIY installation in under 30 minutes.",
    features: ["Rod-type motor", "Silent operation", "App + voice control", "Timer & sunrise/sunset", "Smart Life / Tuya", "Manual override"],
    priceEGP: 2800, priceRange: "Medium",
    store: "Noon / Amazon.eg", storeType: "Online", url: "https://noon.com/egypt-en",
    inStock: true, compatibility: ["Alexa", "Google Home", "Tuya"],
    installation: "DIY", useCase: ["Comfort", "Automation"], sku: "TUYA-CURTAIN-ROD",
  },
  {
    id: "tuya-lock-fp",
    name: "Tuya Smart Lock (Fingerprint + PIN + Card)",
    brand: "Tuya", category: "Smart Locks", subcategory: "WiFi Smart Lock",
    protocol: "WiFi / Bluetooth",
    description: "Budget-friendly smart door lock with all the basics — fingerprint, PIN, card, app control, and a physical key backup for complete peace of mind.",
    features: ["Fingerprint reader", "PIN code access", "Physical key backup", "App control", "Low battery alert", "Tuya app"],
    priceEGP: 3200, priceRange: "Low",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Tuya", "Smart Life"],
    installation: "Technician", useCase: ["Security"], sku: "TUYA-LOCK-FP",
  },
  {
    id: "tuya-smoke-zb",
    name: "Tuya Zigbee Smart Smoke Detector",
    brand: "Tuya", category: "Smart Sensors", subcategory: "Smoke Sensor",
    protocol: "Zigbee",
    description: "Zigbee smoke sensor with loud local alarm and app alerts — triggers automations like unlocking doors or turning on lights when smoke is detected.",
    features: ["85dB alarm", "App notification", "Zigbee 3.0", "Hub required", "Smart automation trigger", "Battery powered"],
    priceEGP: 950, priceRange: "Low",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "SmartThings", "Tuya"],
    installation: "DIY", useCase: ["Security"], sku: "TUYA-ZB-SMOKE",
  },
  {
    id: "tuya-doorbell-2k",
    name: "Tuya Smart Video Doorbell 2K WiFi",
    brand: "Tuya", category: "Smart Doorbells", subcategory: "WiFi Video Doorbell",
    protocol: "WiFi",
    description: "See and speak to whoever's at your door from anywhere — 2K video, motion detection, and night vision. Smart Life app integration.",
    features: ["2K video quality", "Two-way audio", "Night vision", "Motion detection", "Cloud + SD storage", "App alerts"],
    priceEGP: 2200, priceRange: "Medium",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Tuya"],
    installation: "DIY", useCase: ["Security"], sku: "TUYA-DOORBELL-2K",
  },

  // ── HIKVISION SECURITY ─────────────────────────────────────
  {
    id: "hik-ds2cd1043g2",
    name: "Hikvision DS-2CD1043G2-I 4MP IP Camera",
    brand: "Hikvision", category: "Smart Cameras", subcategory: "Wired IP Camera",
    protocol: "PoE / Ethernet",
    description: "Professional IP camera for serious security — 4MP clarity with 30m IR range and H.265 compression for efficient storage.",
    features: ["4MP Full HD", "H.265 compression", "30m IR night vision", "IP67 weatherproof", "PoE powered", "NVR compatible"],
    priceEGP: 2200, priceRange: "Medium",
    store: "B.TECH / Amazon.eg / Jumia", storeType: "Both", url: "https://jumia.com.eg",
    inStock: true, compatibility: ["Hikvision iVMS", "Hik-Connect", "ONVIF"],
    installation: "Technician", useCase: ["Security", "Outdoor"], sku: "HIK-DS2CD1043G2",
  },
  {
    id: "hik-nvr-4ch",
    name: "Hikvision DS-7104NI-Q1/4P 4-Channel NVR + PoE",
    brand: "Hikvision", category: "Security Systems", subcategory: "Network Video Recorder",
    protocol: "PoE / Ethernet",
    description: "4-channel NVR with built-in PoE — power and connect up to 4 IP cameras with a single cable. Supports up to 4K playback.",
    features: ["4 PoE ports", "Supports 4K cameras", "H.265 compression", "1 HDD bay", "Remote viewing", "ONVIF compatible"],
    priceEGP: 3500, priceRange: "Medium",
    store: "B.TECH / Amazon.eg / Jumia", storeType: "Both", url: "https://jumia.com.eg",
    inStock: true, compatibility: ["Hikvision iVMS", "Hik-Connect"],
    installation: "Technician", useCase: ["Security"], sku: "HIK-NVR-4CH",
  },
  {
    id: "hik-colorvu-5mp",
    name: "Hikvision 5MP ColorVu Turret Camera",
    brand: "Hikvision", category: "Smart Cameras", subcategory: "ColorVu Camera",
    protocol: "PoE",
    description: "24/7 full-color camera — captures vivid color video even in complete darkness. No more black-and-white night footage.",
    features: ["5MP ColorVu", "Full color night vision", "Built-in white light", "IP67 weatherproof", "H.265+", "Audio support"],
    priceEGP: 2800, priceRange: "Medium", badge: "Color Night", badgeColor: "aurora",
    store: "B.TECH / Amazon.eg / Raya Shop", storeType: "Both", url: "https://amazon.eg",
    inStock: true, compatibility: ["Hikvision iVMS", "Hik-Connect"],
    installation: "Technician", useCase: ["Security", "Outdoor"], sku: "HIK-COLORVU-5MP",
  },

  // ── SHELLY ────────────────────────────────────────────────
  {
    id: "shelly-plus-1",
    name: "Shelly Plus 1 WiFi Relay Switch",
    brand: "Shelly", category: "Smart Switches", subcategory: "WiFi Relay Module",
    protocol: "WiFi / Bluetooth",
    description: "Professional-grade smart relay — works perfectly with Home Assistant and can function without the cloud for full local control.",
    features: ["1-channel relay", "WiFi + Bluetooth", "Local control (no cloud)", "Home Assistant native", "10A load", "Script support"],
    priceEGP: 850, priceRange: "Low", badge: "HA Favourite", badgeColor: "plasma",
    store: "Amazon.eg", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Home Assistant", "IFTTT"],
    installation: "DIY", useCase: ["Lighting", "Automation"], sku: "SHELLY-PLUS-1",
  },
  {
    id: "shelly-3em",
    name: "Shelly 3EM 3-Phase Energy Monitor",
    brand: "Shelly", category: "Energy Management", subcategory: "3-Phase Energy Meter",
    protocol: "WiFi",
    description: "Professional 3-phase energy monitor — measure every circuit in your home or business and detect wasteful appliances in real time.",
    features: ["3-phase monitoring", "120A clamps", "Real-time power data", "Home Assistant", "Local API", "Web dashboard"],
    priceEGP: 3800, priceRange: "Medium",
    store: "Amazon.eg", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Home Assistant", "IFTTT"],
    installation: "Electrician", useCase: ["Energy Saving"], sku: "SHELLY-3EM",
  },

  // ── SWITCHBOT ─────────────────────────────────────────────
  {
    id: "switchbot-curtain-3",
    name: "SwitchBot Curtain 3 (Track Clip-On Motor)",
    brand: "SwitchBot", category: "Smart Curtains", subcategory: "Clip-On Curtain Motor",
    protocol: "Bluetooth / WiFi",
    description: "The cleverest curtain automation — clips onto your existing curtain track without any installation or wiring. Works in seconds. Matter certified.",
    features: ["Clips to existing curtains", "No wiring", "Solar charging option", "Matter support", "Alexa & Google", "Schedule open/close"],
    priceEGP: 4800, priceRange: "Medium", badge: "No Install", badgeColor: "electric",
    store: "Amazon.eg", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "Matter"],
    installation: "DIY", useCase: ["Comfort", "Automation"], sku: "SWITCHBOT-CURTAIN3",
  },

  // ── BROADLINK ─────────────────────────────────────────────
  {
    id: "broadlink-rm4-pro",
    name: "BroadLink RM4 Pro Universal IR/RF Remote",
    brand: "BroadLink", category: "Smart Climate", subcategory: "Universal IR Remote",
    protocol: "WiFi / IR / RF",
    description: "The most powerful universal remote for smart homes — controls AC units, TVs, fans, and any IR/RF device from anywhere in the world.",
    features: ["IR + RF control", "Works with any AC", "Self-learning remote", "IHC app + Alexa / Google", "Cloud + local control", "IFTTT"],
    priceEGP: 1400, priceRange: "Low",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "IFTTT", "SmartThings"],
    installation: "DIY", useCase: ["Climate", "Automation"], sku: "BROADLINK-RM4PRO",
  },

  // ── PHILIPS HUE ───────────────────────────────────────────
  {
    id: "hue-starter-kit",
    name: "Philips Hue Starter Kit (3 Color Bulbs + Bridge)",
    brand: "Philips Hue", category: "Smart Lighting", subcategory: "Zigbee Lighting Kit",
    protocol: "Zigbee",
    description: "The world's most trusted smart lighting kit — 3 full-color bulbs and the Hue Bridge that unlocks the full ecosystem of 100+ Philips Hue products.",
    features: ["3 x E27 color bulbs", "Hue Bridge hub", "16M colors", "HomeKit / Alexa / Google", "Scenes & routines", "Entertainment mode"],
    priceEGP: 8500, priceRange: "Premium", badge: "Premium Brand", badgeColor: "plasma",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Apple HomeKit", "SmartThings"],
    installation: "DIY", useCase: ["Lighting", "Comfort", "Entertainment"], sku: "HUE-STARTER-KIT",
  },

  // ── ENERGY MANAGEMENT ─────────────────────────────────────
  {
    id: "tuya-energy-meter-din",
    name: "Tuya WiFi DIN-Rail Energy Meter",
    brand: "Tuya", category: "Energy Management", subcategory: "WiFi Energy Monitor",
    protocol: "WiFi",
    description: "DIN-rail energy meter for electrical panels — monitors real-time consumption and sends monthly reports to your app. Designed for Egyptian homes.",
    features: ["Din rail mount", "Real-time kWh tracking", "Monthly reports", "App alerts", "Tuya / Smart Life", "Alexa & Google"],
    priceEGP: 2500, priceRange: "Medium",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "Tuya"],
    installation: "Electrician", useCase: ["Energy Saving"], sku: "TUYA-ENERGY-METER",
  },

  // ── BUNDLES ───────────────────────────────────────────────
  {
    id: "bundle-starter-bedroom",
    name: "Smart Bedroom Starter Bundle",
    brand: "SONOFF", category: "Bundles & Kits", subcategory: "Room Bundle",
    protocol: "WiFi",
    description: "Everything to make one bedroom smart — 2-gang switch, smart bulb, door sensor, and motion sensor. Set up in under an hour.",
    features: ["1x SONOFF T2 2-Gang Switch", "1x Smart RGBW Bulb E27", "1x Door/Window Sensor", "1x Motion Sensor", "Pre-configured in eWeLink", "Installation guide included"],
    priceEGP: 2800, priceRange: "Medium", badge: "Bundle Save 15%", badgeColor: "aurora",
    store: "Aura Smart Home / SONOFF Egypt", storeType: "Both", url: "https://aura.eg",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink"],
    installation: "DIY", useCase: ["Lighting", "Security", "Automation"], sku: "BUNDLE-BEDROOM", featured: true,
  },
  {
    id: "bundle-security-starter",
    name: "Smart Security Starter Bundle",
    brand: "TP-Link Tapo", category: "Bundles & Kits", subcategory: "Security Bundle",
    protocol: "WiFi",
    description: "Complete security starter — outdoor camera, indoor camera, door sensor, and smart hub. Your home protected from day one.",
    features: ["1x Tapo C310 Outdoor Camera", "1x Tapo C200 Indoor Camera", "1x Tapo T110 Door Sensor", "1x Tapo H200 Hub", "All pre-configured", "30-day money-back"],
    priceEGP: 5200, priceRange: "Medium", badge: "Complete Kit", badgeColor: "electric",
    store: "Amazon.eg / Noon", storeType: "Online", url: "https://amazon.eg",
    inStock: true, compatibility: ["Alexa", "Google Home"],
    installation: "DIY", useCase: ["Security", "Automation"], sku: "BUNDLE-SECURITY",
  },
  {
    id: "bundle-villa-package",
    name: "Villa Smart Home Package (Full Home)",
    brand: "SONOFF", category: "Bundles & Kits", subcategory: "Full Home Bundle",
    protocol: "WiFi / Zigbee",
    description: "Complete smart home transformation for villas — NSPanel Pro hub, 10 switches, 5 sensors, smart curtains, energy monitoring, and professional installation included.",
    features: ["1x NSPanel Pro Hub", "10x Smart Switches", "5x Zigbee Sensors", "2x Curtain Motors", "Energy monitor", "Professional installation", "1-year support"],
    priceEGP: 28000, priceRange: "Premium", badge: "Full Home", badgeColor: "plasma",
    store: "SONOFF Egypt / Aura Smart Home", storeType: "Both", url: "https://sonoffegypt.com",
    inStock: true, compatibility: ["Alexa", "Google Home", "eWeLink", "Home Assistant"],
    installation: "Technician", useCase: ["Lighting", "Security", "Energy", "Automation", "Climate"], sku: "BUNDLE-VILLA",
  },
];

export const getBadgeStyle = (badgeColor?: string): string => {
  const styles: Record<string, string> = {
    electric: "bg-electric/20 text-electric border border-electric/30",
    aurora:   "bg-aurora/20 text-aurora border border-aurora/30",
    plasma:   "bg-plasma/20 text-plasma border border-plasma/30",
    ember:    "bg-ember/20 text-ember border border-ember/30",
  };
  return styles[badgeColor || "electric"] || styles.electric;
};
